MODEL_KEY := Yuki
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := \
	BaseColor.png \
	BaseColor.psd \
	Normal.png \
	Normal.psd \
	MatCap.png \
	MatCap.psd \
	Displacement.png \
	Displacement.psd
FILE_COPIED := \
	BaseColor.kra \
	Normal.kra \
	MatCap.kra \
	Displacement.kra \
	WhippedCream.blend
FILE_FROM_BLEND := Yuki.fbx
FILE_MAIN_FBX := Yuki.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
