MODEL_KEY := Cynthea
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := \
	BaseColor.png \
	BaseColor.psd
FILE_COPIED := \
	BaseColor.kra \
	Cynthea.blend \

FILE_FROM_BLEND := Cynthea.fbx
FILE_MAIN_FBX := Cynthea.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
