MODEL_KEY := Mocha
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := \
	BaseColor.png \
	BaseColor.psd \
	Normal.psd \
	Normal.png
FILE_COPIED := \
	BaseColor.kra \
	Normal.kra \
	Mocha.blend

FILE_FROM_BLEND := Mocha.fbx
FILE_MAIN_FBX := Mocha.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
