MODEL_KEY := Shiro
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := \
	BaseColor.png \
	BaseColor.psd \
	Normal.png \
	Normal.psd
FILE_COPIED := \
	BaseColor.kra \
	Normal.kra \
	Shiro.blend
FILE_FROM_BLEND := Shiro.fbx
FILE_MAIN_FBX := Shiro.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
