MODEL_KEY := CactusBunny
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := \
	BaseColor.png \
	BaseColor.psd \
	Normal.png \
	Normal.psd
FILE_COPIED := \
	BaseColor.kra \
	Normal.kra \
	CactusBunny.blend \

FILE_FROM_BLEND := CactusBunny.fbx
FILE_MAIN_FBX := CactusBunny.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
