MODEL_KEY := SweetsDragon
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_FROM_KRA := SweetsDragon.Eye.png
FILE_COPIED := \
	BaseColor.png \
	BaseColorWhite.png \
	Body.Pink.Mask.png \
	Candy.Color.Edited.png \
	Candy.Color.png \
	Fur.Seemless.Displacement.png \
	Fur.Seemless.png \
	Normal.png \
	Other.BaseColor.png \
	Roughness.png \
	Specular.png \
	Stitch.png \
	Strawberry.AO.png \
	Strawberry.Color.png \
	StrawBerry.Normal.png \
	SweetsDragon.Maf.png \
	SweetsDragon.blend
FILE_FROM_BLEND := SweetsDragon.fbx
FILE_MAIN_FBX := SweetsDragon.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
