MODEL_KEY := SexyDicon
README_TEMPLATE := README-for-priced.md
LISENCE_TEMPLATE := LISENCE-for-priced.md
FILE_COPIED := \
	Alpha.png \
	BaseColor.png \
	Normal.png \
	Roughness.png \
	SexyDicon.blend
FILE_FROM_BLEND := SexyDicon.fbx
FILE_MAIN_FBX := SexyDicon.fbx

# scripts
ABS_REPO_ROOT := $(shell git rev-parse --show-toplevel)
include $(ABS_REPO_ROOT)/scripts/Makefile
